# For conda build
package:
  name: pydas
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }} # [unix]
  host:
    - python
    - cython
    - numpy
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}
	
test:
  files:
    - tests
  requires:
    - nose
    - matplotlib
  imports:
    - pydas
    - pydas.dassl
    - pydas.daspk
  commands:
    - nosetests -P --all-modules -v -w tests

about:
  home: http://github.com/ReactionMechanismGenerator/PyDAS
  license: MIT
  summary: "A Python wrapper to several differential algebraic system solvers, namely DASSL and DASPK."
