# For conda build
package:
  name: pydas
  version: "1.0.1"

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }} # number of commits since last git tag (which should be last version bump)

requirements:
  build:
    - gcc # [unix]
    - python 2.7* # for compatibility with RDKit
    - setuptools
    - cython ==0.21
    - numpy 1.9* # for compatibility with RDKit
    - wget
  run:
    - libgcc # [unix]
    - python 2.7* # for compatibility with RDKit
    - numpy 1.9* # for compatibility with RDKit

test:
  requires:
    - nose
    - matplotlib
  imports:
    - pydas
    - pydas.dassl
    - pydas.daspk
  commands:
    - nosetests -P --all-modules -v -w $SRC_DIR/tests

about:
  home: http://github.com/ReactionMechanismGenerator/PyDAS
  license: MIT
  summary: "A Python wrapper to several differential algebraic system solvers, namely DASSL and DASPK."
