# For conda build
package:
  name: pydas
  version: "1.0.1"

source:
  path: .

build:
  number: 2

requirements:
  build:
    - gcc # [unix]
    - python
    - setuptools
    - cython ==0.21
    - numpy
    - wget
  run:
    - libgcc # [unix]
    - python
    - numpy

test:
  requires:
    - nose
    - matplotlib
  imports:
    - pydas
    - pydas.dassl
    - pydas.daspk
  commands:
    - nosetests -P --all-modules -v -w $SRC_DIR/tests

about:
  home: http://github.com/ReactionMechanismGenerator/PyDAS
  license: MIT
  summary: "A Python wrapper to several differential algebraic system solvers, namely DASSL and DASPK."
