# For conda build
package:
  name: pydas
  version: '1.0.4'

source:
  path: ../

build:
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}npy{{ NPY_VER }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - cython
    - numpy
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}
	
test:
  source_files:
    - tests
  requires:
    - matplotlib
  imports:
    - pydas
    - pydas.dassl
    - pydas.daspk
  commands:
    - python -m unittest -v tests/daspkTest.py tests/dasslTest.py

about:
  home: http://github.com/ReactionMechanismGenerator/PyDAS
  license: MIT
  summary: "A Python wrapper to several differential algebraic system solvers, namely DASSL and DASPK."
